---
- name: Backup postgresql config file in redhat
  copy:
    src: "/var/lib/pgsql/{{postgresql_version}}/data/postgresql.conf"
    dest: "/var/lib/pgsql/{{postgresql_version}}/data/postgresql.conf-orig"
    remote_src: true
    force: false
  when: ansible_os_family == "RedHat"
  tags: postgresql-config-backup,install-postgresdb
      
- name: Backup pg_hba config file in redhat
  copy:
    src: "/var/lib/pgsql/{{postgresql_version}}/data/pg_hba.conf"
    dest: "/var/lib/pgsql/{{postgresql_version}}/data/pg_hba.conf-orig"
    remote_src: true
    force: false
  when: ansible_os_family == "RedHat"
  tags: pghba-config-backup,install-postgresdb,postgresql-config-backup

